### ISSUE TITLE
Do you have a example of a data table?

### ISSUE THREAD

**Issue by mranhtu** [insinfo/essential_components#2]

**Comment by insinfo** [comment]
I updated Readme, with an example use of the DataTable component, which shows at the same time the use of SimpleLoading and RestClientGeneric. I'm having little time at work, but I have regularly updated the components because I use it in many projects and all the components have been working very well, but I haven't had time to update the documentation, I updated the example project with DataTable demo, but not I still have a demo of all the components, I will soon update it by creating a gallery of all components with code examples, if you are interested in helping I am available, clone and pull request.

**Comment by mranhtu** [comment]
I tried with your example data table.  But it seems that your data table does not support `List<dynamic>`.
I tried to convert my data from `List<User>` to `RList<User>` but the code didn't work. I don't use `RestClientGeneric`

**Comment by insinfo** [comment]
RestClientGeneric is not required you can use any API to get the data, one thing that is required is the use of RList <your entity that implements the interface>

The use of RList is mandatory because this list has one property that is Total Records, this property is required so that dataTable can paginate the results.

If DataTable gets a dynamic type as it will know what data has to be rendered and how to render it on screen, I accept suggestions, what do you have in mind? What do you suggest?

What error are you getting.
